// Generated register defines for ascon

// Copyright information found in source file:
// Copyright lowRISC contributors (OpenTitan project).

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _ASCON_REG_DEFS_
#define _ASCON_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Number registers for key
#define ASCON_PARAM_NUM_REGS_KEY 4

// Number registers for nonce
#define ASCON_PARAM_NUM_REGS_NONCE 4

// Number registers for input and output data (ad/plaintext/ciphertext)
#define ASCON_PARAM_NUM_REGS_DATA 4

// Number registers for input and output tag
#define ASCON_PARAM_NUM_REGS_TAG 4

// Number of alerts
#define ASCON_PARAM_NUM_ALERTS 2

// Register width
#define ASCON_PARAM_REG_WIDTH 32

// Alert Test Register
#define ASCON_ALERT_TEST_REG_OFFSET 0x0
#define ASCON_ALERT_TEST_REG_RESVAL 0x0u
#define ASCON_ALERT_TEST_RECOV_CTRL_UPDATE_ERR_BIT 0
#define ASCON_ALERT_TEST_FATAL_FAULT_BIT 1

// Initial Key Registers Share 0.
#define ASCON_KEY_SHARE0_KEY_SHARE0_FIELD_WIDTH 32
#define ASCON_KEY_SHARE0_MULTIREG_COUNT 4

// Initial Key Registers Share 0.
#define ASCON_KEY_SHARE0_0_REG_OFFSET 0x4
#define ASCON_KEY_SHARE0_0_REG_RESVAL 0x0u

// Initial Key Registers Share 0.
#define ASCON_KEY_SHARE0_1_REG_OFFSET 0x8
#define ASCON_KEY_SHARE0_1_REG_RESVAL 0x0u

// Initial Key Registers Share 0.
#define ASCON_KEY_SHARE0_2_REG_OFFSET 0xc
#define ASCON_KEY_SHARE0_2_REG_RESVAL 0x0u

// Initial Key Registers Share 0.
#define ASCON_KEY_SHARE0_3_REG_OFFSET 0x10
#define ASCON_KEY_SHARE0_3_REG_RESVAL 0x0u

// Initial Key Registers Share 1.
#define ASCON_KEY_SHARE1_KEY_SHARE1_FIELD_WIDTH 32
#define ASCON_KEY_SHARE1_MULTIREG_COUNT 4

// Initial Key Registers Share 1.
#define ASCON_KEY_SHARE1_0_REG_OFFSET 0x14
#define ASCON_KEY_SHARE1_0_REG_RESVAL 0x0u

// Initial Key Registers Share 1.
#define ASCON_KEY_SHARE1_1_REG_OFFSET 0x18
#define ASCON_KEY_SHARE1_1_REG_RESVAL 0x0u

// Initial Key Registers Share 1.
#define ASCON_KEY_SHARE1_2_REG_OFFSET 0x1c
#define ASCON_KEY_SHARE1_2_REG_RESVAL 0x0u

// Initial Key Registers Share 1.
#define ASCON_KEY_SHARE1_3_REG_OFFSET 0x20
#define ASCON_KEY_SHARE1_3_REG_RESVAL 0x0u

// Input Nonce Register Share 0.
#define ASCON_NONCE_SHARE0_NONCE_FIELD_WIDTH 32
#define ASCON_NONCE_SHARE0_MULTIREG_COUNT 4

// Input Nonce Register Share 0.
#define ASCON_NONCE_SHARE0_0_REG_OFFSET 0x24
#define ASCON_NONCE_SHARE0_0_REG_RESVAL 0x0u

// Input Nonce Register Share 0.
#define ASCON_NONCE_SHARE0_1_REG_OFFSET 0x28
#define ASCON_NONCE_SHARE0_1_REG_RESVAL 0x0u

// Input Nonce Register Share 0.
#define ASCON_NONCE_SHARE0_2_REG_OFFSET 0x2c
#define ASCON_NONCE_SHARE0_2_REG_RESVAL 0x0u

// Input Nonce Register Share 0.
#define ASCON_NONCE_SHARE0_3_REG_OFFSET 0x30
#define ASCON_NONCE_SHARE0_3_REG_RESVAL 0x0u

// Input Nonce Register Share 1.
#define ASCON_NONCE_SHARE1_NONCE_FIELD_WIDTH 32
#define ASCON_NONCE_SHARE1_MULTIREG_COUNT 4

// Input Nonce Register Share 1.
#define ASCON_NONCE_SHARE1_0_REG_OFFSET 0x34
#define ASCON_NONCE_SHARE1_0_REG_RESVAL 0x0u

// Input Nonce Register Share 1.
#define ASCON_NONCE_SHARE1_1_REG_OFFSET 0x38
#define ASCON_NONCE_SHARE1_1_REG_RESVAL 0x0u

// Input Nonce Register Share 1.
#define ASCON_NONCE_SHARE1_2_REG_OFFSET 0x3c
#define ASCON_NONCE_SHARE1_2_REG_RESVAL 0x0u

// Input Nonce Register Share 1.
#define ASCON_NONCE_SHARE1_3_REG_OFFSET 0x40
#define ASCON_NONCE_SHARE1_3_REG_RESVAL 0x0u

// Input Data Register 0.
#define ASCON_DATA_IN_SHARE0_MSG_IN_FIELD_WIDTH 32
#define ASCON_DATA_IN_SHARE0_MULTIREG_COUNT 4

// Input Data Register 0.
#define ASCON_DATA_IN_SHARE0_0_REG_OFFSET 0x44
#define ASCON_DATA_IN_SHARE0_0_REG_RESVAL 0x0u

// Input Data Register 0.
#define ASCON_DATA_IN_SHARE0_1_REG_OFFSET 0x48
#define ASCON_DATA_IN_SHARE0_1_REG_RESVAL 0x0u

// Input Data Register 0.
#define ASCON_DATA_IN_SHARE0_2_REG_OFFSET 0x4c
#define ASCON_DATA_IN_SHARE0_2_REG_RESVAL 0x0u

// Input Data Register 0.
#define ASCON_DATA_IN_SHARE0_3_REG_OFFSET 0x50
#define ASCON_DATA_IN_SHARE0_3_REG_RESVAL 0x0u

// Data Input Register Share 1
#define ASCON_DATA_IN_SHARE1_MSG_IN_FIELD_WIDTH 32
#define ASCON_DATA_IN_SHARE1_MULTIREG_COUNT 4

// Data Input Register Share 1
#define ASCON_DATA_IN_SHARE1_0_REG_OFFSET 0x54
#define ASCON_DATA_IN_SHARE1_0_REG_RESVAL 0x0u

// Data Input Register Share 1
#define ASCON_DATA_IN_SHARE1_1_REG_OFFSET 0x58
#define ASCON_DATA_IN_SHARE1_1_REG_RESVAL 0x0u

// Data Input Register Share 1
#define ASCON_DATA_IN_SHARE1_2_REG_OFFSET 0x5c
#define ASCON_DATA_IN_SHARE1_2_REG_RESVAL 0x0u

// Data Input Register Share 1
#define ASCON_DATA_IN_SHARE1_3_REG_OFFSET 0x60
#define ASCON_DATA_IN_SHARE1_3_REG_RESVAL 0x0u

// Input TAG Register.
#define ASCON_TAG_IN_TAG_IN_FIELD_WIDTH 32
#define ASCON_TAG_IN_MULTIREG_COUNT 4

// Input TAG Register.
#define ASCON_TAG_IN_0_REG_OFFSET 0x64
#define ASCON_TAG_IN_0_REG_RESVAL 0x0u

// Input TAG Register.
#define ASCON_TAG_IN_1_REG_OFFSET 0x68
#define ASCON_TAG_IN_1_REG_RESVAL 0x0u

// Input TAG Register.
#define ASCON_TAG_IN_2_REG_OFFSET 0x6c
#define ASCON_TAG_IN_2_REG_RESVAL 0x0u

// Input TAG Register.
#define ASCON_TAG_IN_3_REG_OFFSET 0x70
#define ASCON_TAG_IN_3_REG_RESVAL 0x0u

// Output Data Register.
#define ASCON_MSG_OUT_MSG_OUT_FIELD_WIDTH 32
#define ASCON_MSG_OUT_MULTIREG_COUNT 4

// Output Data Register.
#define ASCON_MSG_OUT_0_REG_OFFSET 0x74
#define ASCON_MSG_OUT_0_REG_RESVAL 0x0u

// Output Data Register.
#define ASCON_MSG_OUT_1_REG_OFFSET 0x78
#define ASCON_MSG_OUT_1_REG_RESVAL 0x0u

// Output Data Register.
#define ASCON_MSG_OUT_2_REG_OFFSET 0x7c
#define ASCON_MSG_OUT_2_REG_RESVAL 0x0u

// Output Data Register.
#define ASCON_MSG_OUT_3_REG_OFFSET 0x80
#define ASCON_MSG_OUT_3_REG_RESVAL 0x0u

// Output Tag Register.
#define ASCON_TAG_OUT_TAG_OUT_FIELD_WIDTH 32
#define ASCON_TAG_OUT_MULTIREG_COUNT 4

// Output Tag Register.
#define ASCON_TAG_OUT_0_REG_OFFSET 0x84
#define ASCON_TAG_OUT_0_REG_RESVAL 0x0u

// Output Tag Register.
#define ASCON_TAG_OUT_1_REG_OFFSET 0x88
#define ASCON_TAG_OUT_1_REG_RESVAL 0x0u

// Output Tag Register.
#define ASCON_TAG_OUT_2_REG_OFFSET 0x8c
#define ASCON_TAG_OUT_2_REG_RESVAL 0x0u

// Output Tag Register.
#define ASCON_TAG_OUT_3_REG_OFFSET 0x90
#define ASCON_TAG_OUT_3_REG_RESVAL 0x0u

// Control Register.
#define ASCON_CTRL_SHADOWED_REG_OFFSET 0x94
#define ASCON_CTRL_SHADOWED_REG_RESVAL 0x0u
#define ASCON_CTRL_SHADOWED_OPERATION_MASK 0x7u
#define ASCON_CTRL_SHADOWED_OPERATION_OFFSET 0
#define ASCON_CTRL_SHADOWED_OPERATION_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_CTRL_SHADOWED_OPERATION_MASK, .index = ASCON_CTRL_SHADOWED_OPERATION_OFFSET })
#define ASCON_CTRL_SHADOWED_OPERATION_VALUE_ASCON_ENC 0x1
#define ASCON_CTRL_SHADOWED_OPERATION_VALUE_ASCON_DEC 0x2
#define ASCON_CTRL_SHADOWED_OPERATION_VALUE_ASCON_XOF 0x4
#define ASCON_CTRL_SHADOWED_SIDELOAD_KEY_BIT 3
#define ASCON_CTRL_SHADOWED_MASKED_AD_INPUT_BIT 4
#define ASCON_CTRL_SHADOWED_MASKED_MSG_INPUT_BIT 5
#define ASCON_CTRL_SHADOWED_NO_MSG_BIT 6
#define ASCON_CTRL_SHADOWED_NO_AD_BIT 7

// Auxiliary Control Register.
#define ASCON_CTRL_AUX_SHADOWED_REG_OFFSET 0x98
#define ASCON_CTRL_AUX_SHADOWED_REG_RESVAL 0x0u
#define ASCON_CTRL_AUX_SHADOWED_MANUAL_START_TRIGGER_BIT 0
#define ASCON_CTRL_AUX_SHADOWED_FORCE_DATA_OVERWRITE_BIT 1

// Lock bit for Auxiliary Control Register.
#define ASCON_CTRL_AUX_REGWEN_REG_OFFSET 0x9c
#define ASCON_CTRL_AUX_REGWEN_REG_RESVAL 0x1u
#define ASCON_CTRL_AUX_REGWEN_CTRL_AUX_REGWEN_BIT 0

// Block Control Register.
#define ASCON_BLOCK_CTRL_SHADOWED_REG_OFFSET 0xa0
#define ASCON_BLOCK_CTRL_SHADOWED_REG_RESVAL 0x1f000000u
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_START_MASK 0xfffu
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_START_OFFSET 0
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_START_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_START_MASK, .index = ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_START_OFFSET })
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_LAST_MASK 0xfffu
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_LAST_OFFSET 12
#define ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_LAST_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_LAST_MASK, .index = ASCON_BLOCK_CTRL_SHADOWED_DATA_TYPE_LAST_OFFSET })
#define ASCON_BLOCK_CTRL_SHADOWED_VALID_BYTES_MASK 0x1fu
#define ASCON_BLOCK_CTRL_SHADOWED_VALID_BYTES_OFFSET 24
#define ASCON_BLOCK_CTRL_SHADOWED_VALID_BYTES_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_BLOCK_CTRL_SHADOWED_VALID_BYTES_MASK, .index = ASCON_BLOCK_CTRL_SHADOWED_VALID_BYTES_OFFSET })

// Trigger Register.
#define ASCON_TRIGGER_REG_OFFSET 0xa4
#define ASCON_TRIGGER_REG_RESVAL 0x0u
#define ASCON_TRIGGER_START_BIT 0
#define ASCON_TRIGGER_WIPE_BIT 1

// Status Register
#define ASCON_STATUS_REG_OFFSET 0xa8
#define ASCON_STATUS_REG_RESVAL 0x0u
#define ASCON_STATUS_IDLE_BIT 0
#define ASCON_STATUS_STALL_BIT 1
#define ASCON_STATUS_WAIT_EDN_BIT 2
#define ASCON_STATUS_ASCON_ERROR_BIT 3
#define ASCON_STATUS_ALERT_RECOV_CTRL_UPDATE_ERR_BIT 4
#define ASCON_STATUS_ALERT_RECOV_CTRL_AUX_UPDATE_ERR_BIT 5
#define ASCON_STATUS_ALERT_RECOV_BLOCK_CTRL_UPDATE_ERR_BIT 6
#define ASCON_STATUS_ALERT_FATAL_FAULT_BIT 7

// Output Valid Register
#define ASCON_OUTPUT_VALID_REG_OFFSET 0xac
#define ASCON_OUTPUT_VALID_REG_RESVAL 0x0u
#define ASCON_OUTPUT_VALID_DATA_TYPE_MASK 0x7u
#define ASCON_OUTPUT_VALID_DATA_TYPE_OFFSET 0
#define ASCON_OUTPUT_VALID_DATA_TYPE_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_OUTPUT_VALID_DATA_TYPE_MASK, .index = ASCON_OUTPUT_VALID_DATA_TYPE_OFFSET })
#define ASCON_OUTPUT_VALID_TAG_COMPARISON_VALID_MASK 0x3u
#define ASCON_OUTPUT_VALID_TAG_COMPARISON_VALID_OFFSET 3
#define ASCON_OUTPUT_VALID_TAG_COMPARISON_VALID_FIELD \
  ((bitfield_field32_t) { .mask = ASCON_OUTPUT_VALID_TAG_COMPARISON_VALID_MASK, .index = ASCON_OUTPUT_VALID_TAG_COMPARISON_VALID_OFFSET })

// Main FSM State register.
#define ASCON_FSM_STATE_REG_OFFSET 0xb0
#define ASCON_FSM_STATE_REG_RESVAL 0x0u

// Lock bit for Auxiliary Control Register.
#define ASCON_FSM_STATE_REGREN_REG_OFFSET 0xb4
#define ASCON_FSM_STATE_REGREN_REG_RESVAL 0x1u
#define ASCON_FSM_STATE_REGREN_FSM_STATE_REGREN_BIT 0

// Error Register.
#define ASCON_ERROR_REG_OFFSET 0xb8
#define ASCON_ERROR_REG_RESVAL 0x0u
#define ASCON_ERROR_NO_KEY_BIT 0
#define ASCON_ERROR_NO_NONCE_BIT 1
#define ASCON_ERROR_WRONG_ORDER_BIT 2
#define ASCON_ERROR_FLAG_INPUT_MISSMATCH_BIT 3

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _ASCON_REG_DEFS_
// End generated register defines for ascon