// Generated register defines for trial1

// Copyright information found in source file:
// Copyright lowRISC contributors (OpenTitan project).

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _TRIAL1_REG_DEFS_
#define _TRIAL1_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define TRIAL1_PARAM_REG_WIDTH 32

// RW type with one field
#define TRIAL1_RWTYPE0_REG_OFFSET 0x0
#define TRIAL1_RWTYPE0_REG_RESVAL 0xbc614eu

// RW type
#define TRIAL1_RWTYPE1_REG_OFFSET 0x4
#define TRIAL1_RWTYPE1_REG_RESVAL 0x6411u
#define TRIAL1_RWTYPE1_FIELD0_BIT 0
#define TRIAL1_RWTYPE1_FIELD1_BIT 1
#define TRIAL1_RWTYPE1_FIELD4_BIT 4
#define TRIAL1_RWTYPE1_FIELD15_8_MASK 0xffu
#define TRIAL1_RWTYPE1_FIELD15_8_OFFSET 8
#define TRIAL1_RWTYPE1_FIELD15_8_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_RWTYPE1_FIELD15_8_MASK, .index = TRIAL1_RWTYPE1_FIELD15_8_OFFSET })

// RW type with one field and HW rw
#define TRIAL1_RWTYPE2_REG_OFFSET 0x8
#define TRIAL1_RWTYPE2_REG_RESVAL 0x4000400u

// simple RW/HWR type with fields
#define TRIAL1_RWTYPE3_REG_OFFSET 0xc
#define TRIAL1_RWTYPE3_REG_RESVAL 0xee66cc55u
#define TRIAL1_RWTYPE3_FIELD0_MASK 0xffffu
#define TRIAL1_RWTYPE3_FIELD0_OFFSET 0
#define TRIAL1_RWTYPE3_FIELD0_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_RWTYPE3_FIELD0_MASK, .index = TRIAL1_RWTYPE3_FIELD0_OFFSET })
#define TRIAL1_RWTYPE3_FIELD1_MASK 0xffffu
#define TRIAL1_RWTYPE3_FIELD1_OFFSET 16
#define TRIAL1_RWTYPE3_FIELD1_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_RWTYPE3_FIELD1_MASK, .index = TRIAL1_RWTYPE3_FIELD1_OFFSET })

// simple RW type with fields, plus skipto
#define TRIAL1_RWTYPE4_REG_OFFSET 0x200
#define TRIAL1_RWTYPE4_REG_RESVAL 0x80004000u
#define TRIAL1_RWTYPE4_FIELD0_MASK 0xffffu
#define TRIAL1_RWTYPE4_FIELD0_OFFSET 0
#define TRIAL1_RWTYPE4_FIELD0_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_RWTYPE4_FIELD0_MASK, .index = TRIAL1_RWTYPE4_FIELD0_OFFSET })
#define TRIAL1_RWTYPE4_FIELD1_MASK 0xffffu
#define TRIAL1_RWTYPE4_FIELD1_OFFSET 16
#define TRIAL1_RWTYPE4_FIELD1_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_RWTYPE4_FIELD1_MASK, .index = TRIAL1_RWTYPE4_FIELD1_OFFSET })

// RO type
#define TRIAL1_ROTYPE0_REG_OFFSET 0x204
#define TRIAL1_ROTYPE0_REG_RESVAL 0x11111111u

// W1C type with one field
#define TRIAL1_W1CTYPE0_REG_OFFSET 0x208
#define TRIAL1_W1CTYPE0_REG_RESVAL 0xbbccddeeu

// W1C type with fields
#define TRIAL1_W1CTYPE1_REG_OFFSET 0x20c
#define TRIAL1_W1CTYPE1_REG_RESVAL 0x7777eeeeu
#define TRIAL1_W1CTYPE1_FIELD0_MASK 0xffffu
#define TRIAL1_W1CTYPE1_FIELD0_OFFSET 0
#define TRIAL1_W1CTYPE1_FIELD0_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_W1CTYPE1_FIELD0_MASK, .index = TRIAL1_W1CTYPE1_FIELD0_OFFSET })
#define TRIAL1_W1CTYPE1_FIELD1_MASK 0xffffu
#define TRIAL1_W1CTYPE1_FIELD1_OFFSET 16
#define TRIAL1_W1CTYPE1_FIELD1_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_W1CTYPE1_FIELD1_MASK, .index = TRIAL1_W1CTYPE1_FIELD1_OFFSET })

// W1C type with one field, plus HRW
#define TRIAL1_W1CTYPE2_REG_OFFSET 0x210
#define TRIAL1_W1CTYPE2_REG_RESVAL 0xaa775566u

// W1S type with one field, plus HRW
#define TRIAL1_W1STYPE2_REG_OFFSET 0x214
#define TRIAL1_W1STYPE2_REG_RESVAL 0x11224488u

// W0C type with one field, plus HRW
#define TRIAL1_W0CTYPE2_REG_OFFSET 0x218
#define TRIAL1_W0CTYPE2_REG_RESVAL 0xfec8137fu

// R0W1C type with one field, plus HRW
#define TRIAL1_R0W1CTYPE2_REG_OFFSET 0x21c
#define TRIAL1_R0W1CTYPE2_REG_RESVAL 0xaa775566u

// RC type
#define TRIAL1_RCTYPE0_REG_OFFSET 0x220
#define TRIAL1_RCTYPE0_REG_RESVAL 0x77443399u

// WO type
#define TRIAL1_WOTYPE0_REG_OFFSET 0x224
#define TRIAL1_WOTYPE0_REG_RESVAL 0x11223344u

// mixed type with different field access
#define TRIAL1_MIXTYPE0_REG_OFFSET 0x228
#define TRIAL1_MIXTYPE0_REG_RESVAL 0x87654321u
#define TRIAL1_MIXTYPE0_FIELD0_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD0_OFFSET 0
#define TRIAL1_MIXTYPE0_FIELD0_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD0_MASK, .index = TRIAL1_MIXTYPE0_FIELD0_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD1_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD1_OFFSET 4
#define TRIAL1_MIXTYPE0_FIELD1_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD1_MASK, .index = TRIAL1_MIXTYPE0_FIELD1_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD2_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD2_OFFSET 8
#define TRIAL1_MIXTYPE0_FIELD2_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD2_MASK, .index = TRIAL1_MIXTYPE0_FIELD2_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD3_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD3_OFFSET 12
#define TRIAL1_MIXTYPE0_FIELD3_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD3_MASK, .index = TRIAL1_MIXTYPE0_FIELD3_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD4_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD4_OFFSET 16
#define TRIAL1_MIXTYPE0_FIELD4_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD4_MASK, .index = TRIAL1_MIXTYPE0_FIELD4_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD5_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD5_OFFSET 20
#define TRIAL1_MIXTYPE0_FIELD5_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD5_MASK, .index = TRIAL1_MIXTYPE0_FIELD5_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD6_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD6_OFFSET 24
#define TRIAL1_MIXTYPE0_FIELD6_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD6_MASK, .index = TRIAL1_MIXTYPE0_FIELD6_OFFSET })
#define TRIAL1_MIXTYPE0_FIELD7_MASK 0xfu
#define TRIAL1_MIXTYPE0_FIELD7_OFFSET 28
#define TRIAL1_MIXTYPE0_FIELD7_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_MIXTYPE0_FIELD7_MASK, .index = TRIAL1_MIXTYPE0_FIELD7_OFFSET })

// RW type with hwqe
#define TRIAL1_RWTYPE5_REG_OFFSET 0x22c
#define TRIAL1_RWTYPE5_REG_RESVAL 0xbabababau

// RW type with hwext
#define TRIAL1_RWTYPE6_REG_OFFSET 0x230
#define TRIAL1_RWTYPE6_REG_RESVAL 0xc8c8c8c8u

// RO type with hwext
#define TRIAL1_ROTYPE1_REG_OFFSET 0x234
#define TRIAL1_ROTYPE1_REG_RESVAL 0x66aa66aau

// RO type, constant only (hw=none)
#define TRIAL1_ROTYPE2_REG_OFFSET 0x238
#define TRIAL1_ROTYPE2_REG_RESVAL 0x9b908a79u
#define TRIAL1_ROTYPE2_FIELD0_MASK 0xffu
#define TRIAL1_ROTYPE2_FIELD0_OFFSET 0
#define TRIAL1_ROTYPE2_FIELD0_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_ROTYPE2_FIELD0_MASK, .index = TRIAL1_ROTYPE2_FIELD0_OFFSET })
#define TRIAL1_ROTYPE2_FIELD1_MASK 0xffu
#define TRIAL1_ROTYPE2_FIELD1_OFFSET 8
#define TRIAL1_ROTYPE2_FIELD1_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_ROTYPE2_FIELD1_MASK, .index = TRIAL1_ROTYPE2_FIELD1_OFFSET })
#define TRIAL1_ROTYPE2_FIELD2_MASK 0xfffu
#define TRIAL1_ROTYPE2_FIELD2_OFFSET 20
#define TRIAL1_ROTYPE2_FIELD2_FIELD \
  ((bitfield_field32_t) { .mask = TRIAL1_ROTYPE2_FIELD2_MASK, .index = TRIAL1_ROTYPE2_FIELD2_OFFSET })

// RW type with hw-none
#define TRIAL1_RWTYPE7_REG_OFFSET 0x23c
#define TRIAL1_RWTYPE7_REG_RESVAL 0xf6f6f6f6u

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _TRIAL1_REG_DEFS_
// End generated register defines for trial1